### ISSUE TITLE
Layouts errors

### ISSUE THREAD

**Issue by yesszus** [e107inc/agency#8]
Welcome message text is too large in index page

![error](https://cloud.githubusercontent.com/assets/17430115/22503515/6d62907a-e872-11e6-89dd-07c49a8aafbe.png)

Issue 2:
Visible: No Portfolio items  lan text all pages in footer
(Note: not installed theme xml contents.)

![error1](https://cloud.githubusercontent.com/assets/17430115/22503589/c0373f6c-e872-11e6-9833-9d5c8fd9b1b7.png)

![error2](https://cloud.githubusercontent.com/assets/17430115/22503599/c7f8cfb8-e872-11e6-9506-fea1993b24f1.png)

Add changes in theme_shortcodes.php online 210 after work this without footer errors.

https://github.com/e107inc/agency/blob/master/theme_shortcodes.php#L210

`	$text = null;
//	$text = LAN_AG_THEME_14;`

After

![error4](https://cloud.githubusercontent.com/assets/17430115/22503732/5dcbe728-e873-11e6-972d-d5e7508e1be4.png)

**Comment by Jimmi08** [comment]
Welcome message should one line headline as it is in original theme. If you need the smaller text, you can add inline css in theme prefs.

This theme is primary for portfolio, so I've never checked this. Thanks. You can send request or wait when I do it. Thanks for noticing this.
